# load the required libraries
library('zoo')
library('xts')
library('tseries')
library('Quandl')
library('urca')
quandldata = Quandl("NSE/OIL", collapse="monthly", start_date="2001-01-01", type="ts")
plot(quandldata[,1],main='Figure 1: Raw Oil Price Data')
acf(quandldata[,1])
Pacf(quandldata[,1])
adf_test <- adf.test(quandldata[,1],alternative = 'stationary')
print(adf_test)
kpss_test <- kpss.test(quandldata[,1])
print(kpss_test)
udf_test <- ur.df(quandldata[,1], type='trend', lags = 10, selectlags = "BIC")
print(udf_test)
summary(udf_test)
